
OBJ	=	scidbdriver.obj shimclient.obj utils.obj affinetransform.obj tilecache.obj TemporalReference.obj parameter_parser.obj scidb_structs.obj
EXTRAFLAGS = -DHAVE_CURL $(CURL_CFLAGS) $(CURL_INC) $(BOOST_INC)


GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	xcopy /D  /Y *.obj ..\o

clean:
	-del *.obj
	-del *.dll
